name: mopub_flutter
description: A plugin for Mopub Banner, Interstitial & Rewarded Ads in Android & iOS
version: 1.2.2+1
homepage: https://github.com/AnavrinApps/flutter_mopub

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mopub_flutter
        pluginClass: MopubFlutterPlugin
      ios:
        pluginClass: MopubFlutterPlugin
